### PR TITLE
EE-431: add Cargo workspace

### PR DESCRIPTION
**Pull request by henrytill**
This PR 
- adds a Cargo workspace 
- adds a Cargo config file to define a default build target  
- fixes a naming issue with one of the crates
- adds the workspace's `Cargo.lock` back into the project (as is customary)

### CODE REVIEW

**Comment by henrytill** [comment]
* updates `.drone.yml` to use cargo (through a `build.sh`) script
* remove the `Makefile` (which doesn't work with a Cargo workspace and is no longer necessary)
* updates the `README.md`

**Comment by aakoshh** [comment]
I think removing all instructions to install and use the client is a regression in terms of usability. You are pointing the user to the DEVELOPER.md which is about building the node, and I personally have trouble finding all the scattered examples of how to get an environment going and install a client, and then what instructions to use. The Java 11 thing caught me out as well, I don't think I was able to install the package by default.

**Comment by aakoshh** [comment]
It looks like the Developer Guide still has instructions about the [Makefile in this repo](https://github.com/CasperLabs/CasperLabs/blob/dev/DEVELOPER.md#how-to-build-components).

That's the thing about makefiles, if you just tweaked it that interface could have stayed stable even when it does something different under the hood. I think a `make all` is an intuitive and uniform way to build repos without having to delve into the readme. Luckily here the instruction is simple, but `make` can scale when it's a bit more involved.

**Comment by henrytill** [comment]
> I think removing all instructions to install and use the client is a regression in terms of usability. You are pointing the user to the DEVELOPER.md which is about building the node, and I personally have trouble finding all the scattered examples of how to get an environment going and install a client, and then what instructions to use. The Java 11 thing caught me out as well, I don't think I was able to install the package by default.

Yes, we need to do some updates over there as well.  I think with where we are at currently with documentation, it's wasted effort to maintain two separate sources.  This documentation shouldn't be here to serve as better, more concise version of the other docs.  Instead we should continue to focus on improving the main developer documents.

**Comment by henrytill** [comment]
> It looks like the Developer Guide still has instructions about the [Makefile in this repo](https://github.com/CasperLabs/CasperLabs/blob/dev/DEVELOPER.md#how-to-build-components).
>

Yep, will update.

> That's the thing about makefiles, if you just tweaked it that interface could have stayed stable even when it does something different under the hood. I think a `make all` is an intuitive and uniform way to build repos without having to delve into the readme. Luckily here the instruction is simple, but `make` can scale when it's a bit more involved.

I understand your preference for Makefiles, but I think it's important for us to be providing clean, clear examples of building contracts using Cargo, which is the tool that we expect our developers to be using.   We want people to clearly see/identify the expected workflow in our examples repository, and use it as a...well..._example_ for their own work.

As per the "scaling" part, it sorta depends on how the Makefile is written and also what you mean by "scaling".  Cargo has decent support for multi-crate projects with workspaces, and sure, we have to add new crate to the workspace, but I actually prefer this kind of explicit behavior than implicit logic based on `find`, and I would tend to think that it will also be similar to what most Rust developers expect.

**Comment by aakoshh** [comment]
The separate repo with the self contained instructions was a concept which was argued and agreed upon; Granted, not everyone agrees about the separation, which is why we talked about using a Git submodule. In any case I thought there was a need for a less sprawling version of what a dApp developer would need to do, because the information in the main repo is a bit scattered. Only to see all of it destroyed without notice or discussion is demoralising.

About make: I'm not saying that there can't be more direct instructions about cargo, or improvement in the Makefile, but rather that it doesn't hurt to provide the simple interface to the build, and put the details in there, because for example it paves the way to things like building with cargo in a Docker container so people don't _have_ to install all tools on different platforms. It also took care of installing the necessary toolchains, which _everyone_ was caught out by in Miami, another piece of tribal knowledge. Anyway, if you prefer pure readmes, be my guest.

**Comment by henrytill** [comment]
> The separate repo with the self contained instructions was a concept which was argued and agreed upon; Granted, not everyone agrees about the separation, which is why we talked about using a Git submodule. In any case I thought there was a need for a less sprawling version of what a dApp developer would need to do, because the information in the main repo is a bit scattered. Only to see all of it destroyed without notice or discussion is demoralising.

Apologies, it was certainly not my intention to demoralize you or cause any harm whatsoever.   

Given that the team has grown, and some of us were not a part of these early discussions or decisions, perhaps it's worth revisiting some of these questions collectively.   I simply didn't see the guardrail here, it just looked like misplaced duplicate documentation and docker files that were on the road to going stale.  I was under the impression that we would want this repository to do one thing and do it well: provide example contracts.

> About make: I'm not saying that there can't be more direct instructions about cargo, or improvement in the Makefile, but rather that it doesn't hurt to provide the simple interface to the build, and put the details in there, because for example it paves the way to things like building with cargo in a Docker container so people don't _have_ to install all tools on different platforms. It also took care of installing the necessary toolchains, which _everyone_ was caught out by in Miami, another piece of tribal knowledge (although maybe `.cargo/config` takes care of it, I don't know; the `.ci/build.sh` needing the extra installs doesn't suggest that it does). Anyway, if you prefer pure readmes, be my guest.

I think it's reasonable to assume that the intended audience of this repo is prospective contract developers, that they are capable of installing a toolchain based on the information provided in the current README (if they don't already have it installed), and that they would prefer to use the standard tool set.  I also think there's real value in keeping things simple and only having one method of building things, from both a maintenance perspective and a usability one.

 > FYI you left the `.casperlabs/genesis/bonds.txt` file.

Thanks.  Fixed in #26.

**Comment by aakoshh** [comment]
From my experience the audience was myself, Rita, Medha, and everyone else around the table who were asked to test the node. None of us knew cargo, we blindly followed @goral09 instructions and only Tom tried them before, so he vaguely remembered that extra toolchains needed to be installed, because the readme didn't mention them. I made sure all of these are captured and automated. On another occasion we collectively followed along as @RitaatCasperLabs compiled everything from scratch to make sure it works on Mac. @goral09 had to tweak the required installs based on what features the code used, but I also use these to test the docker setup and I'm no cargo buff. Since I see the extras are still necessary in .ci/build.sh I'm not sure what's the benefit of not documenting them, besides the character building and bonding experience it brings to ask for help and figure it out.

**Pull request merged**
